{% set organism_db="/usr/users/ssohrab/CLIP" %}

{% set gff_db = organism_db + "/Annotations" %}
{% set genome_file = organism_db + "/Reference_genome/WholeGenomeFasta/genome.fa" %}
{% set filter_gff = gff_db + "/R64-2-1_genes.gff" %}
{% set negative_set_gff = gff_db + "/R64-2-1_genes.gff" %}
{% set tRNA_gff = gff_db + "/R64-2-1_tRNA_gene.gff" %}
{% set rRNA_gff = gff_db + "/R64-2-1_rRNA_gene.gff" %}
{% set snRNA_gff = gff_db + "/R64-2-1_snRNA_gene.gff" %}
{% set snoRNA_gff = gff_db + "/R64-2-1_snoRNA_gene.gff" %}
{% set intron_gff = gff_db + "/R64-2-1_introns.gff" %}

{% set bootstrap_iter = 2500 %}
{% set n_processes = 6 %}

{% set skip_cp = False %}
{% set skip_hm = False %}
{% set skip_xx = False %}
{% set skip_km = False %}

pipeline:
    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: tRNA-plot CenterPlot
        gff_file: {{ tRNA_gff }}
        output_prefix: tRNA_gene
        downstream_bp: 100
        upstream_bp: 100
        gene_bp: 30
        min_trscr_size_bp: 50
        max_trscr_size_bp: 250
        smoothing_window: 5
        labelCenterA: 5' end
        labelCenterB: 3' end
        labelBody: tRNA body
        remove_tmp_files:  yes
        bootstrap_iter:  {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - CenterPlotBSModule:
        skip: no
        skip: {{ skip_cp }}
        module_info: rRNA-plot CenterPlot
        gff_file: {{ rRNA_gff }}
        output_prefix: rRNA_gene
        downstream_bp: 100
        upstream_bp: 100
        gene_bp: 50
        min_trscr_size_bp: 100
        max_trscr_size_bp: 5000
        smoothing_window: 5
        labelCenterA: 5' end
        labelCenterB: 3' end
        labelBody: rRNA body
        remove_tmp_files: yes
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - GffFilterModule:
        filter_gff: {{ filter_gff }}
        padding_bp: 10
        features:
            - tRNA_gene
            - snRNA_gene
            - snoRNA_gene
            - rRNA_gene
        file_postfix: filtered
        keep_all: yes

    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: Steinmetz CenterPlot 500bp+
        gff_file: {{ gff_db }}/steinmetz_transcripts_tifs_clean_sorted.gff
        output_prefix: steinmetz
        downstream_bp: 500
        upstream_bp: 500
        gene_bp: 250
        min_trscr_size_bp: 500
        max_trscr_size_bp: 5000
        smoothing_window: 21
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: Genebody
        remove_tmp_files: yes
        bootstrap_iter:  {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: Steinmetz CenterPlot 1500bp+
        gff_file: {{ gff_db }}/steinmetz_transcripts_tifs_clean_sorted.gff
        output_prefix: steinmetz
        downstream_bp: 1000
        upstream_bp: 1000
        gene_bp: 750
        min_trscr_size_bp: 1500
        max_trscr_size_bp: 5000
        smoothing_window: 41
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: Genebody
        remove_tmp_files: yes
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: Non-overlapping_ORF-T CenterPlot 1500bp+
        type: center_plot_bs
        gff_file: {{ gff_db }}/nonoverlapping_ORF-T.gff
        output_prefix: nonovl_orf_t
        downstream_bp: 1000
        upstream_bp: 1000
        gene_bp: 750
        min_trscr_size_bp: 1500
        max_trscr_size_bp: 5000
        smoothing_window: 41
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: Genebody
        remove_tmp_files: yes
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: Intron CenterPlot 80bp-200bp
        gff_file: {{ intron_gff }}
        output_prefix: intron
        downstream_bp: 40
        upstream_bp: 40
        gene_bp: 40
        min_trscr_size_bp: 80
        max_trscr_size_bp: 200
        smoothing_window: 5
        labelCenterA: Donor site
        labelCenterB: Acceptor site
        labelBody: Intron body
        remove_tmp_files: yes
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: Intron CenterPlot 150bp+
        gff_file: {{ intron_gff }}
        output_prefix: intron
        downstream_bp: 75
        upstream_bp: 75
        gene_bp: 75
        min_trscr_size_bp: 150
        max_trscr_size_bp: 5000
        smoothing_window: 9
        labelCenterA: Donor site
        labelCenterB: Acceptor site
        labelBody: Intron body
        remove_tmp_files: yes
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

    - HeatmapPlotModule:
        skip: {{ skip_hm }}
        module_info: Steinmetz Heatmap
        gff_file: {{ gff_db }}/steinmetz_transcripts_tifs_clean_sorted.gff
        output_prefix: steinmetz_heatmap_plot
        downstream_bp: 4000
        upstream_bp: 1000
        min_trscr_size_bp: 0
        max_trscr_size_bp: 5000
        xbins: 500
        ybins: 500
        x_pixels: 500
        y_pixels: 500
        remove_tmp_files: yes

    - HeatmapSmallPlotModule:
        skip: {{ skip_hm }}
        module_info: Steinmetz Heatmap Small
        gff_file: {{ gff_db }}/steinmetz_transcripts_tifs_clean_sorted.gff
        output_prefix: steinmetz_heatmap_sm_plot
        downstream_bp: 500
        upstream_bp: 1000
        min_trscr_size_bp: 0
        max_trscr_size_bp: 5000
        xbins: 500
        ybins: 500
        x_pixels: 500
        y_pixels: 500
        remove_tmp_files: yes


    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: CDS 1000+
        gff_file: {{ gff_db }}/salma/CDS_nonoverlapping_sense_TSS_700.gff
        output_prefix: ORF_NoOv_sense_TSS
        downstream_bp: 1000
        upstream_bp: 1000
        gene_bp: 750
        min_trscr_size_bp: 1000
        max_trscr_size_bp: 5000
        smoothing_window: 41
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: genebody
        remove_tmp_files: no
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}


    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: CDS 1000+
        gff_file: {{ gff_db }}/salma/CDS_nonoverlapping_sense_pA_700.gff
        output_prefix: ORF_NoOv_sense_pA
        downstream_bp: 1000
        upstream_bp: 1000
        gene_bp: 750
        min_trscr_size_bp: 1000
        max_trscr_size_bp: 5000
        smoothing_window: 41
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: genebody
        remove_tmp_files: no
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}


    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: CDS 1000+
        gff_file: {{ gff_db }}/salma/TIF_nonoverlapping_sense_TSS_700.gff
        output_prefix: TIF_NoOv_sense_TSS
        downstream_bp: 1000
        upstream_bp: 1000
        gene_bp: 750
        min_trscr_size_bp: 1000
        max_trscr_size_bp: 5000
        smoothing_window: 41
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: genebody
        remove_tmp_files: no
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}


    - CenterPlotBSModule:
        skip: {{ skip_cp }}
        module_info: CDS 1000+
        gff_file: {{ gff_db }}/salma/TIF_nonoverlapping_sense_pA_700.gff
        output_prefix: TIF_NoOv_sense_pA
        downstream_bp: 1000
        upstream_bp: 1000
        gene_bp: 750
        min_trscr_size_bp: 1000
        max_trscr_size_bp: 5000
        smoothing_window: 41
        labelCenterA: TSS
        labelCenterB: pA
        labelBody: genebody
        remove_tmp_files: no
        bootstrap_iter: {{ bootstrap_iter }}
        n_processes: {{ n_processes }}

